import type { GroupResponse } from "@/app/api/groups/type";
import type { NotificationSettingContent } from "@/app/api/notifications/type";
import IcnNew from "@/asset/svg/icn_new.svg?url";

export const tmpGroupData: GroupResponse = {
  id: 0,
  name: "숭실대학교 알고리즘 스터디",
  startDate: "2024.08.13",
  endDate: "2024.09.13",
  introduction:
    "BE Developer로 성장하고 싶은 숭실대학교 학생들이 푸는 알고리즘 스터디입니다",
  groupImage: "",
  role: "OWNER",
  ownerNickname: "jnary",
};

export const notifications = [
  {
    name: "Yesol Song",
    message: "님이 코멘트를 달았어요.",
    date: "5일 전",
    profileImg: IcnNew,
  },
  {
    name: "Yesol Song",
    message:
      "님이 숭실대학교 알고리즘 스터디에 가입했어요. 코멘트를 달며 인사를 나눠보세요.",
    date: "7일 전",
    profileImg: IcnNew,
  },
  {
    name: "Jimin Lee",
    message:
      "님의 SOPT 알고리즘 스터디에 가입이 승인되었어요. 코멘트를 달며 인사를 나눠보세요.",
    date: "10일 전",
    profileImg: IcnNew,
  },
  {
    name: "Yesol Song",
    message: "님이 코멘트를 달았어요.",
    date: "15일 전",
    profileImg: IcnNew,
  },
  {
    name: "Yesol Song",
    message:
      "님이 숭실대학교 알고리즘 스터디에 가입했어요. 코멘트를 달며 인사를 나눠보세요.",
    date: "17일 전",
    profileImg: IcnNew,
  },
  {
    name: "Jimin Lee",
    message:
      "님의 SOPT 알고리즘 스터디에 가입이 승인되었어요. 코멘트를 달며 인사를 나눠보세요.",
    date: "20일 전",
    profileImg: IcnNew,
  },
];

export const NotificationSettingsData: NotificationSettingContent[] = [
  {
    groupId: 15,
    groupName: "test group",
    allNotifications: false,
    newProblem: true,
    newSolution: false,
    newComment: true,
    newMember: false,
    deadlineReached: false,
  },
  {
    groupId: 16,
    groupName: "string",
    allNotifications: false,
    newProblem: false,
    newSolution: false,
    newComment: false,
    newMember: false,
    deadlineReached: false,
  },
  {
    groupId: 17,
    groupName: "This is Choi",
    allNotifications: false,
    newProblem: false,
    newSolution: false,
    newComment: false,
    newMember: false,
    deadlineReached: false,
  },
  {
    groupId: 18,
    groupName: "최주용",
    allNotifications: false,
    newProblem: false,
    newSolution: false,
    newComment: false,
    newMember: false,
    deadlineReached: false,
  },
  {
    groupId: 19,
    groupName: "최주용",
    allNotifications: false,
    newProblem: false,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 20,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 23,
    groupName: "testgroup",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 24,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 25,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 26,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 28,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 29,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 30,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 31,
    groupName: "string",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 32,
    groupName: "테스트 스터디 그룹",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 33,
    groupName: "adsfadsf",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 34,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 35,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 36,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 37,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 38,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 39,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 40,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 41,
    groupName: "최주용 나는 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 42,
    groupName: "최주용 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 43,
    groupName: "최주용 나는 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 44,
    groupName: "올바르게 뜨렴",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 45,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 46,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 47,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 48,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 49,
    groupName: "ㅊㅈㅇㅊㅈㅇ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 50,
    groupName: "토스트 확인용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 51,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 52,
    groupName: "최주용 최주용 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 53,
    groupName: "teststest",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 54,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 55,
    groupName: "sadfasdfasdfa",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 56,
    groupName: "asdfsadf",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 59,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 60,
    groupName: "최주용 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 61,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 62,
    groupName: "ㅊㅈㅇㅊㅈㅇ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 63,
    groupName: "최주용 최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 64,
    groupName: "인하대학교 스터디 그룹",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 65,
    groupName: "인하대학교 스터디 그룹",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 66,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 67,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 68,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 69,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 70,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 71,
    groupName: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 72,
    groupName: "이제는 좀 돼라 ?",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 73,
    groupName: "sdafsadfasdf",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 74,
    groupName: "ㅊㅈㅇ",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 75,
    groupName: "adsfasdfd",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 76,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 78,
    groupName: "나는야 주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 79,
    groupName: "최주용",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 80,
    groupName: "알고헙 릴리즈 언제해",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 82,
    groupName: "왜 그룹 수정은 안되냐고 !",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 84,
    groupName: "jnary 찬양 스터디",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 87,
    groupName: "jnary 찬양 스터디",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 8,
    groupName: "나는 최주용 !",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
  {
    groupId: 89,
    groupName: "그룹 탈퇴해봐 주용아",
    allNotifications: true,
    newProblem: true,
    newSolution: true,
    newComment: true,
    newMember: true,
    deadlineReached: true,
  },
];
