import type { NoticeListResponse } from "@/api/notices/type";

export const tmpData: NoticeListResponse = [
  {
    author: "Yerinewplant",
    noticeId: 45,
    content: "content",
    title: "내일 오프라인 스터디 있습니다. 시간은 09:22입니다. 참고부탁드려요!",
    category: "오프라인 스터디 일정",
    createAt: "2024-09-22 08:20:13",
    isRead: false,
  },
  {
    author: "Angela Santana",
    noticeId: 62,
    content: "content",
    title: "내일 오프라인 스터디 있습니다. 시간은 10:02입니다. 참고부탁드려요!",
    category: "오프라인 스터디 일정",
    createAt: "2024-10-02 08:20:13",
    isRead: true,
  },
  {
    author: "Amber Padilla PhD",
    noticeId: 763,
    content: "content",
    title: "내일 오프라인 스터디 있습니다. 시간은 10:04입니다. 참고부탁드려요!",
    category: "오프라인 스터디 일정",
    createAt: "2024-10-04 08:20:13",
    isRead: false,
  },
  {
    author: "Karen Allen",
    noticeId: 68,
    title:
      "내일 오프라인 스터디 있습니다. 시간은 10:13입니다. 참고부탁드려요!내일 오프라인 스터디 있습니다. 시간은 10:13입니다. 참고부탁드려요!",
    content: "content",
    category: "오프라인 스터디 일정오프라인 스터디 일정",
    createAt: "2024-10-19 08:20:13",
    isRead: false,
  },
  {
    author: "Yerinewplant",
    noticeId: 648,
    content: "content",
    title: "내일 오프라인 스터디 있습니다. 시간은 10:08입니다. 참고부탁드려요!",
    category: "오프라인 스터디 일정",
    createAt: "2024-10-21 08:20:13",
    isRead: false,
  },
  {
    author: "Yerinewplant",
    noticeId: 641,
    content: "content",
    title: "내일 오프라인 스터디 있습니다. 시간은 10:08입니다. 참고부탁드려요!",
    category: "오프라인 스터디 일정",
    createAt: "2024-10-21 08:20:13",
    isRead: false,
  },
  {
    author: "Yerinewplant",
    noticeId: 642,
    content: "content",
    title: "내일 오프라인 스터디 있습니다. 시간은 10:08입니다. 참고부탁드려요!",
    category: "오프라인 스터디 일정",
    createAt: "2024-10-21 08:20:13",
    isRead: false,
  },
  {
    author: "Yerinewplant",
    noticeId: 643,
    content: "content",
    title: "내일 오프라인 스터디 있습니다. 시간은 10:08입니다. 참고부탁드려요!",
    category: "오프라인 스터디 일정",
    createAt: "2024-10-21 08:20:13",
    isRead: false,
  },
];
