import { NotificationSettingsData } from "@/shared/constant/example";
import { theme } from "@/styles/themes.css";

import type { GroupSettingsContent } from "@/app/api/groups/type";
import { STUDY_LIST_COLUMNS } from "@/view/user/setting/GroupList/GroupListTable/constant";
import {
  tableCaptionStyle,
  tableStyle,
  theadStyle,
} from "@/view/user/setting/GroupList/GroupListTable/index.css";
import { NOTIFICATION_SETTINGS_COLUMNS } from "@/view/user/setting/NotificationSetting/NotificationSettingTable/constant";
import { tdStyle } from "@/view/user/setting/NotificationSetting/NotificationSettingTable/index.css";
import type { Meta } from "@storybook/react";
import { DataTable } from ".";

const meta: Meta<typeof DataTable> = {
  title: "Shared/Table",
  component: DataTable,
  parameters: {
    design: {
      type: "figma",
      url: "https://www.figma.com/design/PBHmaVSKndAId6lY6G2qEb/AlgoHub?node-id=491-25321&t=kXe0v1ggMwRlTf9d-4",
    },
  },
  tags: ["autodocs"],
  decorators: (Story) => (
    <div style={{ backgroundColor: theme.color.bg }}>
      <Story />
    </div>
  ),
} satisfies Meta<typeof DataTable>;
export default meta;

const GroupListData: GroupSettingsContent[] = [
  {
    id: 3,
    name: "2025 SCPC 대비",
    startDate: "2025.01.01",
    endDate: "2025.06.15",
    role: "OWNER",
    isBookmarked: false,
    isVisible: true,
    status: "queued",
  },
  {
    id: 5,
    name: "떡잎마을 방범대",
    startDate: "2023.06.01",
    endDate: "2023.12.31",
    role: "ADMIN",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 8,
    name: "나는 최주용 !",
    startDate: "2024.12.05",
    endDate: "2024.12.05",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 15,
    name: "test group",
    startDate: "2024.11.12",
    endDate: "2024.11.29",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 16,
    name: "string",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 17,
    name: "This is Choi",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 18,
    name: "최주용",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 19,
    name: "최주용",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 20,
    name: "최주용",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 23,
    name: "testgroup",
    startDate: "2024.11.14",
    endDate: "2024.11.14",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 24,
    name: "string",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 25,
    name: "string",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 26,
    name: "string",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 28,
    name: "string",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 29,
    name: "string",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 30,
    name: "string",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 31,
    name: "string",
    startDate: "2024.11.15",
    endDate: "2024.11.15",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 32,
    name: "테스트 스터디 그룹",
    startDate: "2024.11.15",
    endDate: "2024.11.25",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 33,
    name: "adsfadsf",
    startDate: "2024.11.12",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 34,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.05",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 35,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.05",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 36,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.05",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 37,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.11",
    endDate: "2024.11.17",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 38,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.11",
    endDate: "2024.11.17",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 39,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.11",
    endDate: "2024.11.17",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 40,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.11",
    endDate: "2024.11.17",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 41,
    name: "최주용 나는 최주용",
    startDate: "2024.11.20",
    endDate: "2024.11.23",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 42,
    name: "최주용 최주용",
    startDate: "2024.11.20",
    endDate: "2024.11.23",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 43,
    name: "최주용 나는 최주용",
    startDate: "2024.11.21",
    endDate: "2024.11.24",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 44,
    name: "올바르게 뜨렴",
    startDate: "2024.11.19",
    endDate: "2024.11.22",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 45,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.11",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 46,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.11",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 47,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.11",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 48,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.11",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 49,
    name: "ㅊㅈㅇㅊㅈㅇ",
    startDate: "2024.11.13",
    endDate: "2024.11.20",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 50,
    name: "토스트 확인용",
    startDate: "2024.11.03",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 51,
    name: "최주용",
    startDate: "2024.11.10",
    endDate: "2024.11.22",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 52,
    name: "최주용 최주용 최주용",
    startDate: "2024.11.11",
    endDate: "2024.11.21",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 53,
    name: "teststest",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 54,
    name: "최주용",
    startDate: "2024.11.13",
    endDate: "2024.11.17",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 55,
    name: "sadfasdfasdfa",
    startDate: "2024.11.12",
    endDate: "2024.11.24",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 56,
    name: "asdfsadf",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 59,
    name: "최주용",
    startDate: "2024.11.11",
    endDate: "2024.11.21",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 60,
    name: "최주용 최주용",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 61,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 62,
    name: "ㅊㅈㅇㅊㅈㅇ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 63,
    name: "최주용 최주용",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 64,
    name: "인하대학교 스터디 그룹",
    startDate: "2024.11.11",
    endDate: "2024.11.12",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 65,
    name: "인하대학교 스터디 그룹",
    startDate: "2024.11.11",
    endDate: "2024.11.12",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 66,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 67,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 68,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 69,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 70,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 71,
    name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 72,
    name: "이제는 좀 돼라 ?",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: false,
    isVisible: false,
    status: "done",
  },
  {
    id: 73,
    name: "sdafsadfasdf",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 74,
    name: "ㅊㅈㅇ",
    startDate: "2024.11.16",
    endDate: "2024.11.16",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 75,
    name: "adsfasdfd",
    startDate: "2024.11.21",
    endDate: "2024.11.23",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 76,
    name: "최주용",
    startDate: "2024.11.11",
    endDate: "2024.11.24",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 78,
    name: "나는야 주용",
    startDate: "2024.11.18",
    endDate: "2024.11.22",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 79,
    name: "최주용",
    startDate: "2024.11.28",
    endDate: "2024.11.30",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 80,
    name: "알고헙 릴리즈 언제해",
    startDate: "2024.11.20",
    endDate: "2024.12.30",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "inProgress",
  },
  {
    id: 82,
    name: "왜 그룹 수정은 안되냐고 !",
    startDate: "2024.11.11",
    endDate: "2024.11.23",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 84,
    name: "jnary 찬양 스터디",
    startDate: "2024.11.23",
    endDate: "2024.11.23",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 87,
    name: "jnary 찬양 스터디",
    startDate: "2024.11.23",
    endDate: "2024.11.23",
    role: "OWNER",
    isBookmarked: true,
    isVisible: false,
    status: "done",
  },
  {
    id: 89,
    name: "그룹 탈퇴해봐 주용아",
    startDate: "2024.11.27",
    endDate: "2024.12.20",
    role: "PARTICIPANT",
    isBookmarked: true,
    isVisible: false,
    status: "inProgress",
  },
];

export const StudyList = {
  render: () => {
    return (
      <DataTable
        title="스터디 리스트"
        rows={GroupListData}
        cols={STUDY_LIST_COLUMNS}
        tableClassName={tableStyle}
        captionClassName={tableCaptionStyle}
        theadClassName={theadStyle}
      />
    );
  },
};

export const NotificationSetting = {
  render: () => {
    return (
      <DataTable
        rows={NotificationSettingsData}
        cols={NOTIFICATION_SETTINGS_COLUMNS}
        tableClassName={tableStyle}
        theadClassName={theadStyle}
        tdClassName={tdStyle}
      />
    );
  },
};
