import type {
  GroupListResponse,
  GroupResponse,
  MemberListResponse,
} from "@/api/groups/type";
import type { SolutionContent } from "@/api/solutions/type";

export const tmpGroupData: GroupResponse = {
  id: 0,
  name: "숭실대학교 알고리즘 스터디",
  startDate: "2024.08.13",
  endDate: "2024.09.13",
  introduction:
    "BE Developer로 성장하고 싶은 숭실대학교 학생들이 푸는 알고리즘 스터디입니다",
  groupImage: "",
  isOwner: true,
  ownerNickname: "jnary",
};

export const tmpUserGroupListData: GroupListResponse = {
  bookmarked: [
    {
      id: 3,
      name: "2025 SCPC 대비",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/c99a0f81-34a8-4acf-8e59-e9d9af988123pexels-jvbuenconcejo-2719301.jpg",
      startDate: "2025.01.01",
      endDate: "2025.06.15",
      introduction: "SCPC 대비 알고리즘 스터디 그룹",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: true,
      isVisible: true,
    },
  ],
  done: [
    {
      id: 5,
      name: "떡잎마을 방범대",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/90c7df07-2a2e-4a07-a8e9-501d44b5da0cjeremy-thomas-jh2KTqHLMjE-unsplash.jpg",
      startDate: "2023.06.01",
      endDate: "2023.12.31",
      introduction: "떡잎마을 방범대 코테 화이팅!",
      ownerNickname: "gamzaKing",
      isOwner: false,
      isBookmarked: false,
      isVisible: false,
    },
    {
      id: 16,
      name: "string",
      groupImage: null,
      startDate: "2024.11.14",
      endDate: "2024.11.14",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 17,
      name: "string",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/e294c044-5c4e-4eb6-a513-fb00af722d29%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
      startDate: "2024.11.14",
      endDate: "2024.11.14",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 18,
      name: "최주용",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/537472da-b8ba-4c0b-8b8b-12fd545038d4%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
      startDate: "2024.11.14",
      endDate: "2024.11.14",
      introduction: "최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 19,
      name: "최주용",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/973eee09-78f3-48dc-9ee2-136694465dcc%E1%84%80%E1%85%B5%E1%86%BA%E1%84%92%E1%85%A5%E1%86%B8%20%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%A1%E1%84%8B%E1%85%B5%E1%86%AF.jpeg",
      startDate: "2024.11.14",
      endDate: "2024.11.14",
      introduction: "최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 20,
      name: "최주용",
      groupImage: null,
      startDate: "2024.11.14",
      endDate: "2024.11.14",
      introduction: "최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 23,
      name: "testgroup",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/4d0c6706-d703-46a0-812e-00b233886a5beberhard-grossgasteiger-NvesrDbsrL4-unsplash.jpg",
      startDate: "2024.11.14",
      endDate: "2024.11.14",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 24,
      name: "string",
      groupImage: null,
      startDate: "2024.11.15",
      endDate: "2024.11.15",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 25,
      name: "string",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/ab754e85-cdea-4f0b-bc13-be47ffdfdda0%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
      startDate: "2024.11.15",
      endDate: "2024.11.15",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 26,
      name: "string",
      groupImage: null,
      startDate: "2024.11.15",
      endDate: "2024.11.15",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 28,
      name: "string",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/d4a19b59-7620-423a-9f0a-92f53c975591IMG_3356.HEIC",
      startDate: "2024.11.15",
      endDate: "2024.11.15",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 29,
      name: "string",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/95179f16-f5e0-44f9-acb0-466c9a6f5d18IMG_3356.HEIC",
      startDate: "2024.11.15",
      endDate: "2024.11.15",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 30,
      name: "string",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/0a7cd578-86e7-42c9-9881-7a7260dfc94fIMG_3356.HEIC",
      startDate: "2024.11.15",
      endDate: "2024.11.15",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 31,
      name: "string",
      groupImage: null,
      startDate: "2024.11.15",
      endDate: "2024.11.15",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 33,
      name: "adsfadsf",
      groupImage: null,
      startDate: "2024.11.12",
      endDate: "2024.11.16",
      introduction: "asdfasdfad",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 34,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.05",
      endDate: "2024.11.16",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 35,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.05",
      endDate: "2024.11.16",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 36,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.05",
      endDate: "2024.11.16",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 37,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.17",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 38,
      name: "이제는 좀 돼라 ?",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/150bcdfa-26b3-4ec4-b3f9-420c275da473%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
      startDate: "2024.11.11",
      endDate: "2024.11.17",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 39,
      name: "이제는 좀 돼라 ?",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/ab5dd5dd-220c-4e33-85f3-2f3c4aa78b54%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%91%E1%85%B5%E1%86%AF%20%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB.png",
      startDate: "2024.11.11",
      endDate: "2024.11.17",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 40,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.17",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 41,
      name: "최주용 나는 최주용",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/06c365c4-75b9-4f41-a6ac-648453b346baKakaoTalk_Photo_2024-05-09-13-42-00.png",
      startDate: "2024.11.20",
      endDate: "2024.11.23",
      introduction: "최주용 나는 최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 42,
      name: "최주용 최주용",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/321a756d-b356-438a-aa51-856a9371979eKakaoTalk_Photo_2024-05-09-13-42-00.png",
      startDate: "2024.11.20",
      endDate: "2024.11.23",
      introduction: "최주용 최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 43,
      name: "최주용 나는 최주용",
      groupImage: null,
      startDate: "2024.11.21",
      endDate: "2024.11.24",
      introduction: "최주용 나는 최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 44,
      name: "올바르게 뜨렴",
      groupImage: null,
      startDate: "2024.11.19",
      endDate: "2024.11.22",
      introduction: "올바르게 뜨렴",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 45,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.16",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 46,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.16",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 47,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.16",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 48,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.16",
      introduction: "이제는 좀 돼라 ?",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 49,
      name: "ㅊㅈㅇㅊㅈㅇ",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/fb2cd4f7-40f1-44c1-b765-35b8e574490fKakaoTalk_Photo_2024-04-21-21-07-40%20004.jpeg",
      startDate: "2024.11.13",
      endDate: "2024.11.20",
      introduction: "ㅊㅈㅇㅊㅈㅇ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 50,
      name: "토스트 확인용",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/8509874e-0178-4c97-ac38-b7af65d12eaetiki.png",
      startDate: "2024.11.03",
      endDate: "2024.11.16",
      introduction: "토스트 확인용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 51,
      name: "최주용",
      groupImage: null,
      startDate: "2024.11.10",
      endDate: "2024.11.22",
      introduction: "sdfadsfasf",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 52,
      name: "최주용 최주용 최주용",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.21",
      introduction: "최주용 최주용 최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 53,
      name: "teststest",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 54,
      name: "최주용",
      groupImage: null,
      startDate: "2024.11.13",
      endDate: "2024.11.17",
      introduction: "최주용최주용최주용최주용최주용최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 55,
      name: "sadfasdfasdfa",
      groupImage: null,
      startDate: "2024.11.12",
      endDate: "2024.11.24",
      introduction: "sadfasdfasdf",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 56,
      name: "asdfsadf",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "asdfadsf",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 59,
      name: "최주용",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.21",
      introduction: "최주용최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 60,
      name: "최주용 최주용",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "최주용 최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 61,
      name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㅁㄹ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 62,
      name: "ㅊㅈㅇㅊㅈㅇ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅊㅈㅇㅊㅈㅇ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 63,
      name: "최주용 최주용",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "최주용 최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 64,
      name: "인하대학교 스터디 그룹",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.12",
      introduction: "하이하이",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 65,
      name: "인하대학교 스터디 그룹",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.12",
      introduction: "하이하이",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 66,
      name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 67,
      name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 68,
      name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 69,
      name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 70,
      name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 71,
      name: "ㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅁㄴㅇㄹㅁㄴㅇㄹㅇㄴㄹ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 72,
      name: "이제는 좀 돼라 ?",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "sadfdsafdf",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: false,
    },
    {
      id: 73,
      name: "sdafsadfasdf",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "sadfasdfdsaf",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 74,
      name: "ㅊㅈㅇ",
      groupImage: null,
      startDate: "2024.11.16",
      endDate: "2024.11.16",
      introduction: "ㅊㅈㅇ",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 75,
      name: "adsfasdfd",
      groupImage: null,
      startDate: "2024.11.21",
      endDate: "2024.11.23",
      introduction: "asdfasdfasdf",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 76,
      name: "최주용",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/dc5cdbd8-f504-4476-a42f-6e52d3d997b6KakaoTalk_Photo_2024-04-08-16-43-59.jpeg",
      startDate: "2024.11.11",
      endDate: "2024.11.24",
      introduction: "최주용과 꾸리",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 78,
      name: "나는야 주용",
      groupImage: null,
      startDate: "2024.11.18",
      endDate: "2024.11.22",
      introduction: "나는야 주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 82,
      name: "왜 그룹 수정은 안되냐고 !",
      groupImage: null,
      startDate: "2024.11.11",
      endDate: "2024.11.23",
      introduction: "왜 그룹 수정은 안되냐고 !",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 84,
      name: "jnary 찬양 스터디",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/7e8eb0cf-85a5-4c21-a375-70a2582b1645IMG_0102.jpeg",
      startDate: "2024.11.23",
      endDate: "2024.11.23",
      introduction: "",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 87,
      name: "jnary 찬양 스터디",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/c213fac9-5780-4b9f-92d8-df6f15f2e059IMG_0102.jpeg",
      startDate: "2024.11.23",
      endDate: "2024.11.23",
      introduction: "",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
  ],
  inProgress: [
    {
      id: 8,
      name: "그래프가 뭐예요?",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/607f62f1-e56c-4833-ab05-3dc322afdba958c1b3e5720b73f274937ec2abfb78de.jpg",
      startDate: "2024.03.26",
      endDate: "2025.12.26",
      introduction: "그래프 중점 알고리즘 스터디",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 15,
      name: "test group",
      groupImage: null,
      startDate: "2024.11.12",
      endDate: "2024.11.29",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 32,
      name: "테스트 스터디 그룹",
      groupImage: null,
      startDate: "2024.11.15",
      endDate: "2024.11.25",
      introduction: "string",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 80,
      name: "알고헙 릴리즈 언제해",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/d219e10f-e4cc-469b-ae5c-61bdae38354b%E1%84%8B%E1%85%B0%E1%86%B8%E1%84%8F%E1%85%A5%E1%86%AB%E1%84%87%E1%85%A6%E1%86%AB%E1%84%89%E1%85%A7%E1%86%AB.png",
      startDate: "2024.11.20",
      endDate: "2024.12.30",
      introduction: "언젠간 하겠지? 그때까지 빠이팅하자",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
    {
      id: 81,
      name: "예정된 스터디",
      groupImage: null,
      startDate: "2024.11.24",
      endDate: "2024.11.27",
      introduction: "예정된 스터디",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
  ],
  queued: [
    {
      id: 3,
      name: "2025 SCPC 대비",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/c99a0f81-34a8-4acf-8e59-e9d9af988123pexels-jvbuenconcejo-2719301.jpg",
      startDate: "2025.01.01",
      endDate: "2025.06.15",
      introduction: "SCPC 대비 알고리즘 스터디 그룹",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: true,
      isVisible: true,
    },
    {
      id: 6,
      name: "DP는 어려워",
      groupImage:
        "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/e9a7437a-02f5-40c8-90fa-e5105b4bcf03joel-henry-zc5_p_31U5g-unsplash.jpg",
      startDate: "2024.12.01",
      endDate: "2025.02.28",
      introduction: "Dynamic Programming을 집중적으로 해봅시다",
      ownerNickname: "dkalsjdk11",
      isOwner: false,
      isBookmarked: false,
      isVisible: false,
    },
    {
      id: 79,
      name: "최주용",
      groupImage: null,
      startDate: "2024.11.28",
      endDate: "2024.11.30",
      introduction: "최주용",
      ownerNickname: "rladmstn",
      isOwner: true,
      isBookmarked: false,
      isVisible: true,
    },
  ],
};

export const tmpSolvedListData: SolutionContent[] = [
  {
    solutionId: 1,
    problemTitle: "막대기",
    problemLevel: 6,
    accuracy: 100,
    submitMemberCount: 3,
    totalMemberCount: 8,
    nickname: "rladmstn",
    profileImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/4c49032c-9f91-40ef-83db-f7e7d5f95b16pexels-eberhardgross-1287142.jpg",
    solvedDateTime: "2024.10.31 05:23:00",
    content: "solution1",
    result: "맞았습니다!!",
    memoryUsage: 256,
    executionTime: 120,
    language: "Java",
    codeLength: 345,
    commentCount: 3,
  },
  {
    solutionId: 1,
    problemTitle: "막대기",
    problemLevel: 6,
    accuracy: 100,
    submitMemberCount: 3,
    totalMemberCount: 8,
    nickname: "rladmstn",
    profileImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/4c49032c-9f91-40ef-83db-f7e7d5f95b16pexels-eberhardgross-1287142.jpg",
    solvedDateTime: "2024.10.31 05:23:00",
    content: "solution1",
    result: "맞았습니다!!",
    memoryUsage: 256,
    executionTime: 120,
    language: "Java",
    codeLength: 345,
    commentCount: 3,
  },
  {
    solutionId: 1,
    problemTitle: "막대기",
    problemLevel: 6,
    accuracy: 100,
    submitMemberCount: 3,
    totalMemberCount: 8,
    nickname: "rladmstn",
    profileImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/4c49032c-9f91-40ef-83db-f7e7d5f95b16pexels-eberhardgross-1287142.jpg",
    solvedDateTime: "2024.10.31 05:23:00",
    content: "solution1",
    result: "맞았습니다!!",
    memoryUsage: 256,
    executionTime: 120,
    language: "Java",
    codeLength: 345,
    commentCount: 3,
  },
  {
    solutionId: 1,
    problemTitle: "막대기",
    problemLevel: 6,
    accuracy: 100,
    submitMemberCount: 3,
    totalMemberCount: 8,
    nickname: "rladmstn",
    profileImage:
      "https://algohubbucket.s3.ap-northeast-2.amazonaws.com/4c49032c-9f91-40ef-83db-f7e7d5f95b16pexels-eberhardgross-1287142.jpg",
    solvedDateTime: "2024.10.31 05:23:00",
    content: "solution1",
    result: "맞았습니다!!",
    memoryUsage: 256,
    executionTime: 120,
    language: "Java",
    codeLength: 345,
    commentCount: 3,
  },
];
export const tmpMemberListData: MemberListResponse = [
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "90%",
    role: "스터디장",
    profileImage: "",
    memberId: 0,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.22",
    achievement: "80%",
    role: "스터디장",
    profileImage: "",
    memberId: 1,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.23",
    achievement: "70%",
    role: "스터디원",
    profileImage: "",
    memberId: 2,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.24",
    achievement: "100%",
    role: "스터디원",
    profileImage: "",
    memberId: 3,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.25",
    achievement: "100%",
    role: "스터디원",
    profileImage: "",
    memberId: 4,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "80%",
    role: "스터디원",
    profileImage: "",
    memberId: 5,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "1%",
    role: "스터디원",
    profileImage: "",
    memberId: 6,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "70%",
    role: "스터디원",
    profileImage: "",
    memberId: 7,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "100%",
    role: "스터디원",
    profileImage: "",
    memberId: 8,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "100%",
    role: "스터디원",
    profileImage: "",
    memberId: 9,
  },
];
