import type { GroupResponse, MemberListResponse } from "@/api/groups/type";
import type { SolutionByIdResponse } from "@/api/solutions/type";

export const tmpGroupData: GroupResponse = {
  id: 0,
  name: "숭실대학교 알고리즘 스터디",
  startDate: "2024.08.13",
  endDate: "2024.09.13",
  introduction:
    "BE Developer로 성장하고 싶은 숭실대학교 학생들이 푸는 알고리즘 스터디입니다",
  groupImage: "",
  isOwner: true,
  ownerNickname: "jnary",
};

export const tmpSolvedListData: SolutionByIdResponse[] = [
  {
    solutionId: 1,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 2,
    nickname: "jnaryadsf",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 3,
    nickname: "jnaryqf",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 4,
    nickname: "jnaryewgb",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 5,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 6,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 7,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 8,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 9,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 10,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 11,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 12,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 13,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 14,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 15,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 16,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 17,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 18,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 19,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
  {
    solutionId: 20,
    nickname: "jnary",
    profileImage: "",
    solvedDateTime: "2024.09.21 21:21:59",
    content: "#include <iostream>",
    result: "맞았습니다",
    memoryUsage: 2020,
    executionTime: 0,
    language: "C++",
    codeLength: 21,
    commentCount: 13,
  },
];

export const tmpMemberListData: MemberListResponse = [
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "90%",
    role: "스터디장",
    profileImage: "",
    memberId: 0,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.22",
    achievement: "80%",
    role: "스터디장",
    profileImage: "",
    memberId: 1,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.23",
    achievement: "70%",
    role: "스터디원",
    profileImage: "",
    memberId: 2,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.24",
    achievement: "100%",
    role: "스터디원",
    profileImage: "",
    memberId: 3,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.25",
    achievement: "100%",
    role: "스터디원",
    profileImage: "",
    memberId: 4,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "80%",
    role: "스터디원",
    profileImage: "",
    memberId: 5,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "1%",
    role: "스터디원",
    profileImage: "",
    memberId: 6,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "70%",
    role: "스터디원",
    profileImage: "",
    memberId: 7,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "100%",
    role: "스터디원",
    profileImage: "",
    memberId: 8,
  },
  {
    nickname: "jnary",
    joinDate: "2024.09.21",
    achievement: "100%",
    role: "스터디원",
    profileImage: "",
    memberId: 9,
  },
];
